import { z } from 'zod'
import { MozaikAgent } from '@mozaik-ai/core'
import { parseAgentResult } from '../mozaik/helpers'
import { getNotionMcpTools, getNotionMcpTool } from '../notion/mcp'
import { notifyUser } from '../notion/api'
import { spektrumGenerateTool } from '../spektrum/client'

export interface BuildInput {
  pageId: string
  userId: string
  proxyBaseUrl: string
}

export interface BuildOutput {
  appUrl: string
  projectId: string
  taskId: string
}

const PageContentSchema = z.object({
  title: z.string(),
  content: z.string().describe('All text content from the page, concatenated'),
})

export async function runBuildWorkflow(input: BuildInput): Promise<BuildOutput> {
  const { pageId, userId, proxyBaseUrl } = input

  const notionTools = await getNotionMcpTools()

  // ── Step 1: Read page content ───────────────────────────────────────
  console.log('[build:1] reading page content...')

  const readerAgent = new MozaikAgent({
    model: 'gpt-5-mini',
    tools: notionTools.filter(t => t.name === 'API-get-block-children'),
    structuredOutput: PageContentSchema,
    messages: [{
      role: 'system',
      content:
        'You read Notion pages and extract all text content. ' +
        'Concatenate all paragraph, heading, bulleted list, numbered list, to-do, ' +
        'and callout text into a single string. Preserve structure with newlines. ' +
        'Ignore embed blocks, dividers, and metadata.',
    }],
  })

  const readRaw = await readerAgent.act(
    `Read the Notion page ${pageId}. Use API-get-block-children with block_id="${pageId}".
    Extract the page title and all text content from the blocks.
    Return the title and concatenated content.`
  )

  const page = parseAgentResult<z.infer<typeof PageContentSchema>>(readRaw)
  console.log(`[build:1] "${page.title}" — ${page.content.length} chars`)

  if (!page.content.trim()) {
    throw new Error('Page has no text content. Write a description of what you want to build.')
  }

  // ── Step 2: Build with Spektrum ─────────────────────────────────────
  console.log('[build:2] generating with Spektrum...')

  // Pass page content directly as task description, with minimal framing
  const taskDescription = `${page.content}

## Technical notes
- Use React, Tailwind CSS, Recharts (if charts needed)
- If the app needs external data, fetch from: ${proxyBaseUrl}/api/data
- If the app needs to submit data, POST to: ${proxyBaseUrl}/api/data/create with { databaseId, properties }
- Dark theme (#0f172a bg) unless the description says otherwise
- Mobile-responsive, clean modern design`

  const built = await spektrumGenerateTool.invoke({
    owner: userId,
    task_title: page.title,
    task_description: taskDescription.slice(0, 3000),
  }) as { appUrl: string; projectId: string; taskId: string }

  console.log(`[build:2] deployed: ${built.appUrl}`)

  // ── Step 3: Embed into Notion ───────────────────────────────────────
  console.log('[build:3] embedding into Notion...')

  const appendBlocks = await getNotionMcpTool('API-patch-block-children')
  await appendBlocks.invoke({
    block_id: pageId,
    children: [
      { type: 'divider', divider: {} },
      {
        type: 'heading_2',
        heading_2: {
          rich_text: [{ type: 'text', text: { content: `🚀 ${page.title}` } }],
        },
      },
      { type: 'embed', embed: { url: built.appUrl } },
      {
        type: 'paragraph',
        paragraph: {
          rich_text: [
            { type: 'text', text: { content: 'Generated by ' } },
            { type: 'text', text: { content: 'vizion', link: { url: 'https://github.com/Lotus015/vizion' } } },
          ],
        },
      },
    ],
  })

  await notifyUser(pageId, userId, `Your app "${page.title}" is ready! 🚀`)

  console.log('[build] complete:', built.appUrl)
  return {
    appUrl: built.appUrl,
    projectId: built.projectId,
    taskId: built.taskId,
  }
}
